(assert (Usuario (id u1)))
(assert (Posee_Plataforma (usuario u1) (plataforma "PC")))
(assert (Posee_Plataforma (usuario u1) (plataforma "PS4")))
(assert (Prefiere_Genero (usuario u1) (genero "RPG")))
(assert (Prefiere_Genero (usuario u1) (genero "Aventura")))
(assert (No_Gusta_Genero (usuario u1) (genero "Terror")))
(assert (Prefiere_Complejidad (usuario u1) (nivel "Alta")))
(assert (Prefiere_Duracion (usuario u1) (tipo "Larga")))
(assert (Prefiere_Multiplayer (usuario u1) (tipo "Si")))
(assert (Edad_Usuario (usuario u1) (edad 17)))
(assert (Gusto_Juego (usuario u1) (juego g1)))
(assert (Jugo_Juego (usuario u1) (juego g1)))

(assert (Juego (id g1)))
(assert (Titulo_Juego (juego g1) (titulo "Dragon Quest XI")))
(assert (Tiene_Genero (juego g1) (genero "RPG")))
(assert (Disponible_En (juego g1) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g1) (nivel "Alta")))
(assert (Tiene_Duracion (juego g1) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g1) (tipo "No")))
(assert (Clasificacion_Edad (juego g1) (clasificacion "13+")))

(assert (Juego (id g2)))
(assert (Titulo_Juego (juego g2) (titulo "Persona 5")))
(assert (Tiene_Genero (juego g2) (genero "RPG")))
(assert (Disponible_En (juego g2) (plataforma "PS4")))
(assert (Tiene_Complejidad (juego g2) (nivel "Alta")))
(assert (Tiene_Duracion (juego g2) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g2) (tipo "No")))
(assert (Clasificacion_Edad (juego g2) (clasificacion "16+")))
(assert (Similar_A (juego1 g2) (juego2 g1)))

(assert (Juego (id g3)))
(assert (Titulo_Juego (juego g3) (titulo "Silent Hill")))
(assert (Tiene_Genero (juego g3) (genero "Terror")))
(assert (Disponible_En (juego g3) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g3) (nivel "Media")))
(assert (Tiene_Duracion (juego g3) (tipo "Corta")))
(assert (Tiene_Multiplayer (juego g3) (tipo "No")))
(assert (Clasificacion_Edad (juego g3) (clasificacion "18+")))

(assert (Juego (id g4)))
(assert (Titulo_Juego (juego g4) (titulo "Monster Hunter World")))
(assert (Tiene_Genero (juego g4) (genero "Aventura")))
(assert (Disponible_En (juego g4) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g4) (nivel "Alta")))
(assert (Tiene_Duracion (juego g4) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g4) (tipo "Si")))
(assert (Clasificacion_Edad (juego g4) (clasificacion "13+")))
